In [33]:
pip install pandas

Requirement already satisfied: pandas in c:\users\sidde\anaconda3\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sidde\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sidde\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sidde\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sidde\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [18]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\sidde\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\sidde\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [34]:
pip install pymysql

Collecting pymysql
  Using cached pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Using cached pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [19]:
#Data load

import pandas as pd

df = pd.read_excel("sales_raw_500.xlsx")

In [20]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
515      1389 2024-02-12    Vikas  North   Laptop  17924  12145
516      1496 2023-04-24    Kiran  North  Printer  23434  16388
517      1031 2023-02-19    Vikas   East  Printer  58883  43579
518      1317 2023-07-05     Aman  North   Laptop  76781  66865
519      1409 2024-01-16    Pooja  North  Monitor  19969  13586

[520 rows x 7 columns]

In [21]:
#Duplicate remove

df = df.drop_duplicates()

In [22]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
498      1499        NaT    Pooja   West   Mobile  59266  44326
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[500 rows x 7 columns]

In [23]:
#fix date column

df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [24]:
df = df.dropna(subset=['Order_Date'])

In [25]:
df

     Order_ID Order_Date Customer Region  Product  Sales   Cost
0        1001 2023-01-13    Rohit  South   Mobile  23289  19118
1        1002 2023-10-07     Aman   West   Laptop   8905   5593
2        1003 2023-11-05    Rahul  South  Monitor  59987  39959
3        1004 2024-02-19    Rahul  South  Printer  49597  33892
4        1005 2024-01-26   Anjali  North   Laptop  54797  34468
..        ...        ...      ...    ...      ...    ...    ...
494      1495 2023-10-18    Rahul  South  Monitor  46709  40931
495      1496 2023-04-24    Kiran  North  Printer  23434  16388
496      1497 2023-06-27   Anjali  South   Laptop  49007  35970
497      1498 2023-05-08     Aman   East   Tablet  19160  15636
499      1500 2023-10-07    Vikas  North  Printer  34567  22426

[482 rows x 7 columns]

In [26]:
df['Profit'] = df['Sales'] -df['Cost']
df['Year'] = df['Order_Date'].dt.year
df['Month'] = df['Order_Date'].dt.month

In [27]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
494,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
495,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
496,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
497,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
499,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [28]:
df.to_csv('sales_cleaned.csv',index=False)

#data = python + Excel + SQL

In [29]:
import pandas as pd
from sqlalchemy import create_engine

In [30]:
df = pd.read_csv('sales_cleaned.csv')

In [31]:
df

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1
...,...,...,...,...,...,...,...,...,...,...
477,1495,2023-10-18,Rahul,South,Monitor,46709,40931,5778,2023,10
478,1496,2023-04-24,Kiran,North,Printer,23434,16388,7046,2023,4
479,1497,2023-06-27,Anjali,South,Laptop,49007,35970,13037,2023,6
480,1498,2023-05-08,Aman,East,Tablet,19160,15636,3524,2023,5
481,1500,2023-10-07,Vikas,North,Printer,34567,22426,12141,2023,10

In [35]:
engine = create_engine('mysql+pymysql://root:Des%40i2405@localhost:3306/salesdb')

#%40 = @

In [36]:
df.to_sql(name='sales_data',con=engine, if_exists='replace', index = False)

482